# Generated by Django 5.1 on 2024-09-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_address_alter_hotel_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
