# Generated by Django 5.1 on 2024-09-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('chech_in', models.DateField(blank=True)),
                ('check_out', models.DateField(blank=True)),
                ('no_of_person', models.PositiveSmallIntegerField()),
                ('lunch', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('bike_rent', models.BooleanField(default=False)),
                ('car_rent', models.BooleanField(default=False)),
            ],
        ),
    ]
