# Generated by Django 5.1 on 2024-09-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_chech_in_booking_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_person',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
