# Generated by Django 5.1 on 2024-09-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_no_of_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_person',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
